import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import CartProvider from "./components/Provider";
import ShoppingCart from "./components/ShoppingCart";
import { Footer } from "./components/Footer";

const poppins = Poppins({ 
  weight:'500', subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        <CartProvider>
       <Navbar/>
       <ShoppingCart/>
        {children}
        </CartProvider>
        <Footer/>
      </body>
    </html>
  );
}
